server:
  port: 9999
spring:
  application:
    name: librarySalesSystem
  jpa:
    show-sql: true
  datasource:
    url: jdbc:h2:mem:xwj_db;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: root
    password: 123456